name: Custom
description: Use this for custom issues. Please do NOT create blank issues
title: "[OTHER]"
body:
  - type: markdown
    attributes:
      value: "# Other issue"
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Feel free to check out other awesome plugins by **wpnizzle** [here](https:/wpnizzle.com).
